export const en = {
  meta: { title: 'Janzu in Riviera Maya — Wu Wei Water', description: 'Janzu aquatic bodywork in warm water in Riviera Maya, Mexico. Explore individual and two-person sessions with Wu Wei Water.' },
  nav: ['Janzu', 'Experience', 'Sessions', 'About', 'FAQ'], book: 'Book', menu: 'Open menu', close: 'Close menu', language: 'Language', skip: 'Skip to content',
  hero: { before: 'Let the water ', emphasis: 'carry', after: ' you.', description: 'Janzu is a guided aquatic bodywork session in warm water. Experience it with Wu Wei Water in Riviera Maya, Mexico.', book: 'Book a session', discover: 'Discover Janzu', label: 'Experience Janzu', location: 'Riviera Maya · Mexico' },
  janzu: { label: 'The practice', title: 'What is Janzu?', paragraphs: ['Janzu is an aquatic bodywork practice experienced in warm water.', 'During a session, your body is gently supported and guided through flowing movements, stretches, stillness and, when appropriate, short underwater immersions.', 'There is nothing you need to perform. You simply allow yourself to be held by the water.'], quote: ['Every session is different.', 'Let the water take you where you need to go.'] },
  experience: { label: 'The experience', title: 'A journey in four movements', steps: [{ title: 'Arrive', description: 'Take a moment to connect, breathe and prepare for the experience.' }, { title: 'Float', description: 'Your body is supported in warm water while movement gradually becomes effortless.' }, { title: 'Let go', description: 'Movement, stillness and water create space to release control and simply experience.' }, { title: 'Integrate', description: 'After the session, there is time to rest and notice what remains.' }] },
  reasons: { label: 'Why people come', intro: 'People come to Janzu to explore', items: ['deep relaxation', 'slowing down', 'body awareness', 'presence', 'trust', 'letting go', 'connection with water', 'emotional space', 'curiosity', 'something new'], statement: ['Nothing to achieve.', 'Nothing to perform.', 'Just water, movement and presence.'] },
  sessions: { label: 'Sessions', title: 'Choose your water', items: [{ title: 'Janzu Experience', duration: '60–75 minutes', description: 'A complete individual aquatic bodywork experience.', cta: 'Experience Janzu' }, { title: 'Deep Water Journey', duration: '90 minutes', description: 'A slower, more spacious experience with additional time for arrival and integration.', cta: 'Explore' }, { title: 'Janzu for Two', duration: '', description: 'Two individual water journeys designed for partners, couples or friends who want to share the experience.', cta: 'Ask about sessions' }] },
  philosophy: { label: 'Philosophy', title: 'Why Wu Wei?', paragraphs: ['Wu Wei (無為) is a Taoist principle often translated as effortless action or non-forcing.', 'Water embodies this naturally. It does not struggle with the path. It responds. It adapts. It flows.', "Wu Wei Water brings this principle into embodied experience — creating a space where you don’t need to force relaxation, transformation or movement.", 'Sometimes the invitation is simply to stop doing and allow yourself to be carried.'], statement: ['Water does not force.', 'It flows.'] },
  practitioner: { label: 'Practitioner', title: 'Meet Andre', paragraphs: ["I’m Andre Ram, an aquatic bodywork practitioner and creator of Wu Wei Water.", 'My work explores the meeting point between water, movement, presence and surrender.', 'Through Janzu, I create spaces where the body can soften, movement can become effortless and the water itself becomes part of the experience.'] },
  testimonials: { label: 'Words from the water', selector: 'Show reflection', note: 'Illustrative reflections; not client reviews.', items: [{ quote: 'For the first time in a long time, I felt I didn’t have to control anything.' }, { quote: 'I came curious. I left lighter, and very still inside.' }, { quote: 'A moment to slow down, float and simply be.' }] },
  location: { label: 'Location', title: 'Currently in Riviera Maya', description: 'Sessions take place in warm water at selected private pools in Riviera Maya, Mexico. Other locations and private sessions may be available on request.', current: 'Riviera Maya, Mexico — Now' },
  faq: { label: 'Questions', title: 'Before you arrive', items: [{ question: 'How do I book a Janzu session?', answer: 'Use the booking link to send a message. We will confirm availability, the pool location and any details you need before your session.' }, { question: 'Where do Janzu sessions take place?', answer: 'Sessions take place in selected private warm-water pools in Riviera Maya, Mexico. The exact location is confirmed when you arrange your session.' }, { question: 'Do I need to know how to swim?', answer: 'You do not need to perform any swimming movements. You are supported throughout the session. Share your comfort level with water beforehand so we can discuss the right approach for you.' }, { question: 'Will I go underwater?', answer: 'Only if you feel comfortable and give your consent. Immersion is always optional. You can stay at the surface, change your mind or pause at any time.' }, { question: 'What should I bring?', answer: 'Bring comfortable swimwear, a towel and drinking water. We will confirm any location-specific details before your session.' }, { question: 'How long does a session last?', answer: 'The Janzu Experience lasts 60–75 minutes. The Deep Water Journey allows 90 minutes, including more time to arrive and integrate. Timing for two people is arranged individually.' }, { question: 'What temperature is the water?', answer: 'Sessions use comfortably warm water. The exact temperature depends on the selected pool and conditions; please ask when arranging your session.' }, { question: 'Is Janzu suitable for everyone?', answer: 'Suitability is individual. Please discuss any health conditions, pregnancy, recent surgery or concerns before booking. If you are unsure, consult a qualified healthcare professional. Janzu is a wellness experience and does not replace medical care.' }, { question: 'What happens after the session?', answer: 'There is time to rest, return at your own pace and notice how you feel. Leave a little space in your day, drink water and share anything you would like to discuss.' }] },
  contact: { label: 'Experience Janzu', title: 'Ready to meet the water?', lines: ['You don’t need to know what to expect.', 'Come as you are.'], cta: 'Book your session', message: 'Hello! I’d like to book a Janzu session.', fallback: 'To arrange your session, send us a message on Instagram.', instagramCta: 'Message on Instagram' },
  tagline: 'Move with water. Not against it.',
  media: { hero: 'A person floating underwater with sunlight rippling across their body', janzu: 'A practitioner gently supporting a person floating in warm water', practitioner: 'Reference portrait of a practitioner standing in a pool at golden hour', location: 'A private pool surrounded by lush greenery at dusk' },
};
export type Dictionary = typeof en;
